global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper:2181']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-master:6379', 'redis-slave:6380']

  - job_name: 'redis-sentinel'
    static_configs:
      - targets: ['redis-sentinel:26379']
